Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty32"
    config.ssh.forward_agent="true"
    config.ssh.forward_x11="true"

    config.vbguest.auto_update = false
    config.vbguest.no_remote = true

  # VirtualBox specific settings
    config.vm.provider "virtualbox" do |vb|
        vb.default_nic_type = "82540EM"
        vb.gui = false
        vb.cpus = 2
        vb.memory = "4096"
    end
end