# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "mwrock/Windows2012R2"

  config.vm.synced_folder "./data", "/vagrant"

  config.vbguest.auto_update = false
  config.vbguest.no_remote = true
  
end